name: 书吧管理员模块
description: '书友会后台书吧管理员模块'
author:
    - wxf
    - 984818992@qq.com
version: 1.0.0
enabled: true
menus:
    finance:
        icon: icon-home
        path: '/bar'
        text: 书吧管理员
        children:
            -
                icon: icon-home
                path: /bar/index
                text: 主页
                submodule: false
                created_at: 2017-10-20 00:00:00
            -
                icon: icon-star
                text: 书吧管理
                submodule: true
                created_at: 2017-10-20 00:00:00
                children:
                    -
                        icon: icon-star
                        path: /bar/group
                        text: 书吧信息
                        created_at: 2017-10-20 00:00:00
                    -
                        icon: icon-people
                        path: /bar/group/user
                        text: 用户列表
                        created_at: 2017-10-20 00:00:00
                    -
                        icon: icon-screen-desktop
                        path: /bar/blog
                        text: 帖子列表
                        created_at: 2017-10-20 00:00:00
                    -
                        icon: icon-note
                        path: /bar/column
                        text: 专栏列表
                        created_at: 2017-10-20 00:00:00
            -
                icon: icon-book-open
                text: 书架管理
                submodule: true
                created_at: 2017-10-20 00:00:00
                children:
                    -
                        icon: icon-book-open
                        path: /bar/book
                        text: 书架列表
            -
                icon: icon-bubble
                text: 消息管理
                submodule: true
                created_at: 2017-10-20 00:00:00
                children:
                    -
                        icon: icon-bubble
                        path: /bar/message
                        text: 历史消息
            -
                icon: icon-screen-desktop
                text: 订单管理
                submodule: true
                created_at: 2017-10-20 00:00:00
                children:
                    -
                        icon: icon-screen-desktop
                        path: /bar/order
                        text: 订单列表
            -
                icon: icon-screen-desktop
                text: 财务管理
                submodule: true
                created_at: 2017-10-20 00:00:00
                children:
                    -
                        icon: icon-screen-desktop
                        path: /bar/finance
                        text: 财务信息