name: 管理员模块
description: '书友会后台管理员模块'
author:
    - wxf
    - 984818992@qq.com
version: 1.0.0
enabled: true
menus:
    finance:
        icon: icon-home
        path: '/admin'
        text: 管理员
        children:
            -
                icon: icon-home
                path: /admin/index
                text: 主页
                submodule: false
                created_at: 2017-10-20 00:00:00
            -
                icon: icon-book-open
                text: 贝壳图书
                submodule: true
                created_at: 2017-10-20 00:00:00
                children:
                    -
                        icon: icon-book-open
                        path: /admin/book
                        text: 书架列表
                        created_at: 2017-10-20 00:00:00
                    -
                        icon: icon-book-open
                        path: /admin/buy/book/list
                        text: 0元购书列表
                        created_at: 2018-04-02 00:00:00
            -
                icon: icon-user
                text: 用户管理
                submodule: true
                created_at: 2017-10-20 00:00:00
                children:
                    -
                        icon: icon-people
                        path: /admin/user
                        text: 用户列表
            -
                icon: icon-bubble
                text: 消息管理
                submodule: true
                created_at: 2017-10-20 00:00:00
                children:
                    -
                        icon: icon-bubble
                        path: /admin/message
                        text: 历史消息
            -
                icon: icon-bubble
                text: 订单管理
                submodule: true
                created_at: 2017-10-20 00:00:00
                children:
                    -
                        icon: icon-screen-desktop
                        path: /admin/order
                        text: 订单列表
            -
                icon: icon-screen-desktop
                text: 财务管理
                submodule: true
                created_at: 2017-10-20 00:00:00
                children:
                    -
                        icon: icon-screen-desktop
                        path: /admin/finance
                        text: 财务详情